mod 'gabe-ngrok', '1.0.5'
mod 'puppet-archive', '4.1.0'
mod 'puppetlabs-concat', '6.0.0'
mod 'puppetlabs-yumrepo_core', '1.0.3'
mod 'puppetlabs-translate', '2.0.0'
mod 'puppetlabs-stdlib', '6.0.0'
mod 'puppet-yum', '4.0.0'
mod 'puppetlabs-apt', '7.0.1'
mod 'elastic-elastic_stack', '6.3.1'
mod 'elastic-kibana', '6.3.1'
mod 'richardc-datacat', '0.6.2'
mod 'elastic-elasticsearch', '6.3.3'
mod 'elastic-logstash', '6.1.5'
mod 'custom-elk',
  :git => 'https://github.com/LightlyH/custom-elk.git'
